### ISSUE TITLE
萌宠报错反馈

### ISSUE THREAD

**Issue by yogayyy** [JDHelloWorld/jd_scripts#109]
东东萌宠: API查询请求失败 ‼️‼️
"read ECONNRESET"

❗️东东萌宠, 错误!

❗️东东萌宠, 错误!
TypeError: Cannot read property 'code' of undefined
    at slaveHelp (/jd/scripts/jd_pet.js:288:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async jdPet (/jd/scripts/jd_pet.js:134:7)
    at async /jd/scripts/jd_pet.js:72:7

**Comment by JDHelloWorld** [comment]
网络波动
