### ISSUE TITLE
jd_cfd.ts 加速卡火爆 美人鱼后出错

### ISSUE THREAD

**Issue by jim114042** [JDHelloWorld/jd_scripts#168]
加速卡任务失败 {
  data: {
    awardStatus: 0,
    completedTimes: 0,
    dateTypeExtra: '',
    updateTime: 0,
    userStatusConfigExtra: ''
  },
  msg: '亲,活动太火爆了,请稍后再试吧!',
  ret: 1015
}

发现美人鱼🧜‍♀️

/home/myid/jd/scripts/jd_cfd.ts:41
  strPrizePool?: string,
                      ^
TypeError: Cannot read properties of null (reading '1')
    at /home/myid/jd/scripts/jd_cfd.ts:593:76
    at step (/home/myid/jd/scripts/jd_cfd.ts:41:23)
    at Object.next (/home/myid/jd/scripts/jd_cfd.ts:22:53)
    at fulfilled (/home/myid/jd/scripts/jd_cfd.ts:13:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by JDHelloWorld** [comment]
fixed
