### ISSUE TITLE
jd_necklace_new.js  fs/promises  error

### ISSUE THREAD

**Issue by badasslittlepig** [JDHelloWorld/jd_scripts#77]
🔔点点券二代目, 开始!
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /Users/wangsong/Documents/node_code/jd_script_now/jd_necklace_new.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/wangsong/Documents/node_code/jd_script_now/jd_necklace_new.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wangsong/Documents/node_code/jd_script_now/jd_necklace_new.js'
  ]
}

line 3  change：
     const fs = require('fs').promises;

**Comment by badasslittlepig** [comment]
node -v 
v12.22.0
npm -v
6.14.11

**Comment by JDHelloWorld** [comment]
node -v => 16.4.1
npm  -v => 7.19.1
